# mail | actionmailer
using_gem: actionmailer
from: noreply@server-watch.com

# if `using_gem: actionmailer`
actionmailer:
  perform_deliveries: true
  raise_delivery_errors: true
  delivery_method: smtp
  smtp_settings:
    address: smtp.gmail.com
    port: 587
    domain: wealth-park.com
    user_name: noreply@wealth-park.com
    password: Xb^*7#f!
    authentication: plain
    enable_starttls_auto: true
