# mail | actionmailer
using_gem: actionmailer
from: noreply@server-watch.com

# if `using_gem: actionmailer`
actionmailer:
  perform_deliveries: true
  raise_delivery_errors: true
  delivery_method: smtp
  smtp_settings:
    address: smtp.gmail.com
    port: 587
    domain: rjc.co.jp
    user_name: noreply@rjc.co.jp
    password: yE3amE2TkRzuYmahvQad
    authentication: plain
    enable_starttls_auto: true
